# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.cache/wt [current_project]
set_property parent.project_path C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/sources_1/new/UC.vhd
  C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/sources_1/new/FDN.vhd
  C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/sources_1/new/ADDN.vhd
  C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/sources_1/new/SLRN.vhd
  C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/sources_1/new/Impartitor.vhd
  C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/sources_1/new/SevenSegment.vhd
  C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/sources_1/new/ImplementarePlaca.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/SSC/MetodaFaraRefacereaRestului/MetodaFaraRefacereaRestului.srcs/constrs_1/new/constraints.xdc]


synth_design -top ImplementarePlaca -part xc7a100tcsg324-1


write_checkpoint -force -noxdef ImplementarePlaca.dcp

catch { report_utilization -file ImplementarePlaca_utilization_synth.rpt -pb ImplementarePlaca_utilization_synth.pb }
